apiVersion: v1
kind: Service
metadata:
  name: cowrie-honeypot
spec:
  type: NodePort
  selector:
    app: cowrie-honeypot
  ports:
    - name: ssh
      port: 22
      targetPort: 2222
      nodePort: 30022
    - name: telnet
      port: 23
      targetPort: 2223
      nodePort: 30023