apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.16.3-debian-opensearch-1.0
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          capabilities:
            add:
            - DAC_READ_SEARCH
        env:
        - name: FLUENT_OPENSEARCH_HOST
          value: "opensearch.monitoring.svc.cluster.local"
        - name: FLUENT_OPENSEARCH_PORT
          value: "9200"
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: pods
          mountPath: /var/log/pods
        - name: docker
          mountPath: /var/lib/docker  # Mount entire docker directory
        - name: pos-file
          mountPath: /var/log/fluentd-containers.log.pos  # Explicit POS file mount
        - name: config-volume
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: pods
        hostPath:
          path: /var/log/pods
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: pos-file
        hostPath:
          path: /var/log/fluentd-containers.log.pos
          type: FileOrCreate
      - name: config-volume
        configMap:
          name: fluentd-config