apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      format json
    </source>

    <match **>
      @type elasticsearch
      host opensearch-cluster-master.logging.svc.cluster.local
      port 9200
      scheme http
      user admin
      password OpenSearch@123
      logstash_format true
      logstash_prefix fluentd
      include_tag_key true
      type_name _doc
      reconnect_on_error true
      reload_connections true
    </match>


