apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/*.gz"]
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.**
      read_from_head true
      <parse>
        @type multiline  # Handle multiline logs
        format_firstline /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z/  # Match ISO8601 timestamps
        format1 /^(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z) (?<log>.*)/
        <parse>  # Nested JSON parser for parsed logs
          @type json
          time_format %Y-%m-%dT%H:%M:%S.%NZ
          keep_time_key true
          emit_invalid_record_to_error false
          unmatched_lines  # Skip non-JSON logs
        </parse>
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      skip_labels false
      skip_container_metadata false
      skip_master_url true
      # Prevent 404 errors for deleted pods:
      skip_namespace_metadata true  # Optional: Skip fetching namespace metadata
      cache_size 1000  # Increase cache size (default: 100)
      cache_ttl 3600  # Time-to-live for cached entries (default: 3600)
      watch true  # Watch for pod changes (requires RBAC permissions)
      # Reduce API calls:
      skip_labels true  # Skip labels if unused
      skip_container_metadata true  # Skip container metadata if unused
      retry_on_404_max_times 0  # Do not retry on 404 errors
      retry_on_404_interval 0  # Disable retry interval
    </filter>

    <match kubernetes.**>
      @type opensearch
      scheme http
      host opensearch.monitoring.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix fluentd
      time_key @timestamp
      utc_index true
      request_timeout 30s
      reload_connections false
      suppress_type_name true
      verify_es_version_at_startup false
      <buffer>
        flush_interval 10s
        retry_forever true
        retry_type exponential_backoff
        retry_wait 2s
        retry_max_interval 120s
        chunk_limit_size 20MB
        queue_limit_length 64
      </buffer>
    </match>