apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  opensearch-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: OpenSearch
      type: grafana-opensearch-datasource
      access: proxy
      url: http://opensearch.monitoring.svc.cluster.local:9200
      basicAuth: true
      basicAuthUser: admin
      jsonData:
        database: fluentd-*
        version: 2.11.0
        flavor: opensearch
        timeField: '@timestamp'
        logLevelField: 'level'
        logMessageField: 'message'
        maxConcurrentShardRequests: 5
      secureJsonData:
        basicAuthPassword: admin
