apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: honeypots
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
