# honeypot-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-honeypot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-honeypot
  template:
    metadata:
      labels:
        app: ssh-honeypot
    spec:
      containers:
      - name: ssh-honeypot
        image: docker.io/panubo/sshd:latest
        ports:
        - containerPort: 22
        env:
        - name: SSH_USERS
          value: "user:1000:1000:/bin/sh:/bin/sh"
        - name: SSH_ENABLE_PASSWORD_AUTH
          value: "true"
        - name: SSH_ENABLE_PUBKEY_AUTH
          value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: ssh-honeypot
spec:
  type: NodePort
  selector:
    app: ssh-honeypot
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30222
