# honeypot-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ssh-honeypot
  namespace: monitoring
spec:
  selector:
    app: ssh-honeypot
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22 
  type: ClusterIP