# honeypot-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-honeypot
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-honeypot
  template:
    metadata:
      labels:
        app: ssh-honeypot
    spec:
      containers:
      - name: ssh-honeypot
        image: docker.io/panubo/sshd:latest
        ports:
        - containerPort: 22
        env:
        - name: SSH_USERS
          value: "user:1000:1000:/bin/bash:supersecret"
        - name: SSH_ENABLE_PASSWORD_AUTH
          value: "true"
        - name: SSH_ENABLE_PUBKEY_AUTH
          value: "false"