apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: monitoring
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/opensearch/logs"]
        volumeMounts:
        - name: logs
          mountPath: /usr/share/opensearch/logs
      containers:
      - name: opensearch
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          privileged: false
          allowPrivilegeEscalation: false
        image: opensearchproject/opensearch:2.11.0
        env:
        - name: discovery.type
          value: single-node
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms1g -Xmx1g -Dopensearch.cgroups.hierarchy.override=/ -Dopensearch.logger.level=ERROR"
        - name: plugins.security.disabled
          value: "true"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9600
          name: transport
        volumeMounts:
        - name: data
          mountPath: /usr/share/opensearch/data
        - name: logs
          mountPath: /usr/share/opensearch/logs
      volumes:
      - name: logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi