apiVersion: apps/v1
kind: Deployment
metadata:
  name: dionaea
  labels:
    app: dionaea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dionaea
  template:
    metadata:
      labels:
        app: dionaea
    spec:
      containers:
      - name: dionaea
        image: dinotools/dionaea
        ports:
        - containerPort: 21   # FTP
        - containerPort: 42   # WINS
        - containerPort: 80   # HTTP
        - containerPort: 135  # RPC
        - containerPort: 445  # SMB
        - containerPort: 3306 # MySQL
        - containerPort: 1433 # MSSQL
        securityContext:
          privileged: true
        volumeMounts:
        - name: dionaea-data
          mountPath: /opt/dionaea/var/dionaea
      volumes:
      - name: dionaea-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: dionaea
spec:
  selector:
    app: dionaea
  ports:
  - name: ftp
    port: 21
    targetPort: 21
  - name: http
    port: 80
    targetPort: 80
  - name: smb
    port: 445
    targetPort: 445
  - name: mysql
    port: 3306
    targetPort: 3306
  - name: mssql
    port: 1433
    targetPort: 1433
  type: ClusterIP
